export const SEARCH_CITIES_REQUEST = 'SEARCH_CITIES_REQUEST';
export const SEARCH_CITIES_SUCCESS = 'SEARCH_CITIES_SUCCESS';
export const SEARCH_CITIES_FAILURE = 'SEARCH_CITIES_FAILURE';
export const SEARCH_TEXT_CHANGE = 'SEARCH_TEXT_CHANGE';
